### ISSUE TITLE
Can't read train json data

### ISSUE THREAD

**Issue by felicitywang** [soroushjavdan/NLIbert#1]
Hi, thanks for the interesting work and open-sourcing the code.

I ran into memory issues when reading the repaired json data with pandas.

When I tried `json.loads(json.load(f))` I got `json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 69819 (char 69818)` error because of a `"` in the text:

```
>>> test[69810:69830]     
'hildren"s charity"],'
```

It seems that the solution should be fairly straightforward but I can't seem to find any. Could you suggest some memory-efficient ways to load the train data?

Thank you very much.

**Comment by soroushjavdan** [comment]
Hi, thanks for the interest
The problem is in the data_repairer.py file. I will try to put the time to resolve it. However, you might still get the memory error after correcting the training file, because the dataset is so big!

**Comment by felicitywang** [comment]
@soroushjavdan Thank you. Are there any updates on this? Or are there suggestions for the hardware to run this? When you said "you might still get the memory error" is it for reading datasets or is it for training afterwards?

Thank you.

**Comment by Stanwang1210** [comment]
Hey guys!
I don't think it's a memory issue.
I met memory error after running data_repairer.py file.
After several attempts and tests, it seems the file is still corrupted in terms of json format, not due its size.
Can we re-open this issue?
