### ISSUE TITLE
About create_test_predictions

### ISSUE THREAD

**Issue by kuroko730** [soroushjavdan/NLIbert#2]
Hi, thanks for the great work!
Training part and val part can run smoothly.

But, while I'm running the create_test_predictions part, there is some error in those line.

Traceback (most recent call last):
  File "I:/DNLI/NLIbert-master/train.py", line 18, in <module>
    cm.create_test_predictions("./pred.csv")
  File "I:\DNLI\NLIbert-master\bert_classifier.py", line 196, in create_test_predictions
    tests_features = data_reader.convert_examples_to_features(self.x_test, [-1] * len(self.test_df),
AttributeError: 'ClassificationModel' object has no attribute 'x_test'

https://github.com/soroushjavdan/NLIbert/blob/0c133344c1aacadae60d2f630ab47018600646b0/bert_classifier.py#L194
I'm wondering what is x_text mean?

and in the next line, same problem with x_test_ids.
 https://github.com/soroushjavdan/NLIbert/blob/0c133344c1aacadae60d2f630ab47018600646b0/bert_classifier.py#L222

Thank you very much.

**Comment by soroushjavdan** [comment]
Hi, thanks for your interest, and sorry for answering with delay.
I checked it out, and it was my mistake.  Actually, x_test should be changed to test_df.
I am going to fix both of these problems in the following days. 
Cheers

**Comment by soroushjavdan** [comment]
Hi @kuroko730,
I fixed the bug!! let me know if there are any problems.
Cheers

**Comment by kuroko730** [comment]
Hi,
Thanks for your attention.
And thanks for this great project again !
Now this test program can run smoothly.
